---
# tasks file for httpd
- name: Install the specified version of Apache HTTPD
  yum:
    name: "{{ http_version }}"
    state: installed
    allow_downgrade: yes

- name: Allow port 80 firewall
  firewalld:
    service: http
    permanent: yes
    state: present

- name: Set systemd to start Apache on boot
  systemd:
    name: httpd
    enabled: yes
    daemon_reload: yes
    state: started

- name: Restart Apache HTTPD gracefully
  command: httpd -k graceful
