---
# tasks file for httpd
- name: Fetch Apache Package from remote rpm_location
  get_url:
    dest: /tmp/apache.rpm
    url: "{{ rpm_location }}"

- name: Get current version of Apache installed
  package_facts:
    manager: rpm
  register: packages

- name: Install the specified version of Apache HTTPD
  yum:
    name: /tmp/apache.rpm
    state: installed
    allow_downgrade: yes
    skip_broken: yes

- name: Allow port 80 firewall
  firewalld:
    service: http
    permanent: yes
    state: enabled
    immediate: yes

- name: Set systemd to start Apache on boot
  systemd:
    name: httpd
    enabled: yes
    daemon_reload: yes
    state: started

- name: Restart Apache HTTPD gracefully
  command: httpd -k graceful
